name: Playwright Test Suite

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write  # allows github-actions[bot] to push, create tags, etc.  

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-playwright allure-pytest requests faker
          playwright install --with-deps

      # 4️⃣ Run tests
      - name: Run tests
        run: pytest --alluredir=reports

      # 5️⃣ Upload Allure results as artifact
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: reports

      # 6️⃣ Install Allure Commandline
      - name: Install Allure Commandline
        run: npm install -g allure-commandline

      # 7️⃣ Generate Allure report
      - name: Generate Allure report
        run: allure generate reports --clean -o allure-report

      # 8️⃣ Deploy Allure report to GitHub Pages
      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
